version: '3.6'
services:
  nginx:
    build: 
      context: ./nginx 
    volumes: 
      - static_volume:/app/static
      - media_volume:/app/img
    ports: 
    - 80:80 
    depends_on:
      - web 
    restart: "on-failure"
  web:
    build: 
      context: ./
    volumes: 
      - static_volume:/app/static
      - media_volume:/app/img
    command: sh -c "python manage.py migrate &&
                    gunicorn maxcard.wsgi:application --bind 0.0.0.0:8000 --reload" 
    image: tuxiboule/maxcard
    restart: "on-failure"

volumes:
  static_volume:
  media_volume:
