# Generated by Django 5.0.4 on 2024-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIID', models.CharField(blank=True, max_length=10000)),
                ('NAME', models.CharField(blank=True, max_length=10000)),
                ('TYPE', models.CharField(blank=True, max_length=10000)),
                ('FRAMETYPE', models.CharField(blank=True, max_length=10000)),
                ('DESC', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
