# Generated by Django 5.0.4 on 2024-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='IMG',
            field=models.URLField(blank=True),
        ),
    ]
